services:
  backend:
    build:
      context: .
    container_name: nearhelp-backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    ports:
      - "5002:3007"
    volumes:
      - ./uploads:/app/uploads

  frontend:
    build:
      context: ../nearhelp-frontend
      args:
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
    container_name: nearhelp-frontend
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - backend
    ports:
      - "5001:3000"
