export enum NotificationType {
	BOOKING_UPDATED = 'BOOKING_UPDATED',
	NEW_MESSAGE = 'NEW_MESSAGE',
	NEW_REVIEW = 'NEW_REVIEW',
	NEW_FOLLOWER = 'NEW_FOLLOWER',
	ARTICLE_COMMENT = 'ARTICLE_COMMENT',
	SYSTEM = 'SYSTEM',
}
