export enum ServiceCategory {
	PLUMBING = 'PLUMBING',
	GAS_LINE = 'GAS_LINE',
	ELECTRICITY = 'ELECTRICITY',
	WATER_LINE = 'WATER_LINE',
	BATHROOM_PLUMBING = 'BATHROOM_PLUMBING',
	BASEMENT_PLUMBING = 'BASEMENT_PLUMBING',
	REMODELING = 'REMODELING',
	CLEANING = 'CLEANING',
}
